name = "yasumaro-formal"
version = "0.1.0"
defaultTargets = ["YasumaroTests", "testgen"]

[[lean_lib]]
name = "Yasumaro"

[[lean_exe]]
name = "YasumaroTests"
root = "YasumaroTests"

[[lean_exe]]
name = "testgen"
root = "TestGen"
